#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

set -e

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

JAVA_OPTS=${JAVA_OPTS:-}
GRADLE_OPTS=${GRADLE_OPTS:-}

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

OS=$(uname -s)
case "$OS" in
  CYGWIN* ) cygwin=true  ;;
  Darwin* ) darwin=true  ;;
  MSYS* | MINGW* ) msys=true ;;
  NONSTOP* ) nonstop=true ;;
  * ) ;;
esac

APP_HOME=$(cd "${0%/*}" && pwd -P) || exit

WRAPPER_JAR=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
WRAPPER_SHARED_JAR=$APP_HOME/gradle/wrapper/gradle-wrapper-shared.jar
WRAPPER_CLI_JAR=$APP_HOME/gradle/wrapper/gradle-cli.jar

CLASSPATH=$WRAPPER_JAR:$WRAPPER_SHARED_JAR:$WRAPPER_CLI_JAR

if [ ! -r "$WRAPPER_JAR" ]; then
  die "ERROR: gradle-wrapper.jar not found. Expected at: $WRAPPER_JAR"
fi

if [ ! -r "$WRAPPER_SHARED_JAR" ]; then
  die "ERROR: gradle-wrapper-shared.jar not found. Expected at: $WRAPPER_SHARED_JAR"
fi

if [ ! -r "$WRAPPER_CLI_JAR" ]; then
  die "ERROR: gradle-cli.jar not found. Expected at: $WRAPPER_CLI_JAR"
fi

if [ -n "${JAVA_HOME:-}" ] ; then
    JAVA_EXEC="$JAVA_HOME/bin/java"
else
    JAVA_EXEC="java"
fi

command -v "$JAVA_EXEC" >/dev/null 2>&1 || die "ERROR: Java not found. Set JAVA_HOME or ensure 'java' is on PATH."

if [ -n "${GRADLE_OPTS:-}" ]; then
    GRADLE_OPTS="$GRADLE_OPTS"
fi

exec "$JAVA_EXEC" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    -Dorg.gradle.appname="$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"

